### ISSUE TITLE
Newtonsoft JSON

### ISSUE THREAD

**Issue by Chizaruu** [silverua/slay-the-spire-map-in-unity#23]
Unity now supports the Newtonsoft JSON as a standalone package, and you can easily access it by following these instructions:

1. Visit the following link to access the Newtonsoft JSON package documentation: https://docs.unity3d.com/Packages/com.unity.nuget.newtonsoft-json@3.0/manual/index.html

2. Once you are on the page, you can learn more about the package and how to use it in your Unity projects.

3. To start using the package in your project, import it through the Package Manager. The package name is com.unity.nuget.newtonsoft-json@3.0.

Only bringing it up as I wanted to remove the dependence on Analytics/In-app purchases packages.

**Comment by silverua** [comment]
Thanks, that's helpful info. 

I am hesitant to change anything related to this atm because: 
- I started this project on Unity 2019. One of the goals is to keep it compatible with slightly older versions. 
- Since 2019, Unity tried a lot of different things with Newtonsoft Json. First, you had to include it manually. Then with some versions it was included automatically with some Unity packages. Then, again, it was excluded and it had to be added manually. So, no consistency on their end unfortunately. 
- The package is not present in the Package Manager on Unity versions 2019.3.11, 2021.3.4. Should it be added as a git url or something like that?

**Comment by Chizaruu** [comment]
Yeah, you need to include it via git URL for Unity 2019/2021. (It's added to the Package Manager in 2022 I believe)

It **should** be compatible with Unity 2019 but would need to test to make sure.

**Comment by Chizaruu** [comment]
Btw, 2019.3.11 isn't the latest version for 2019 LTS
![image](https://user-images.githubusercontent.com/59434446/225266933-0680d018-f65f-45d3-8fd6-471399ba7d2d.png)

**Comment by silverua** [comment]
I gave up yesterday and updated master to Unity 2021. 
Reasons:
- When people opened the 2019 project from master and upgraded it to newer versions, they got null ref errors related to Vector3 serialization by Newtonsoft, which is not a good initial experience.
- Newtonsoft is included on that version of 2021 as a part of one of the Unity's default packages. Maybe ads or analytics or something like that. 
- Discovered that UILineRenderer behavior in the SampleSceneUI is different on 2019 and 2021. The code to connect the nodes with lines and have equal offsets from nodes on either side is different on 2019 and 2021. So, decided to roll with a later version that most people will probably use.

**Comment by Chizaruu** [comment]
![image](https://user-images.githubusercontent.com/59434446/225271770-c1847e12-6f05-4115-ab94-f38a5fd90247.png)
